eureka:
  client:
    region: default
  registryFetchIntervalSeconds: 5
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/

cloud:
    config:
      discovery:
        enabled: true # This is required
        service-id: configserver # Config Server's eureka registry name
      enabled: true # This is default true already
